# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AutoCreateModel' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AppFramework


  
  pod 'KVOController', '~> 1.2.0'
  pod 'MBProgressHUD', '~> 0.9.1'
end
